# Minimal semantic-release configuration example
# To use: Copy to project root as .releaserc.toml

[semantic_release]
version_toml = ["pyproject.toml:project.version"]
branch = "main"
upload_to_repository = false
upload_to_release = true

# Basic commit types
[semantic_release.commit_parser_options]
minor_types = ["feat"]
patch_types = ["fix", "perf"]